### ISSUE TITLE
[BUG] Non-standard tag markup in YAML frontmatter

### ISSUE THREAD

**Issue by pdxmph** [basicmachines-co/basic-memory#118]
## Bug Description
Basic Memory doesn't follow YAML markup syntax when creating a tags key. 

## Steps To Reproduce

Run command `basic-memory tool write-note --title "This is a tags test" --content "Some test content" --tags basicmemory --folder Notes`

## Expected Behavior

```yaml
title: This is a tags test
type: note
permalink: notes/this-is-a-tags-test
tags:
  - basicmemory
 ```

## Actual Behavior
Frontmatter of resulting note:

```yaml
title: This is a tags test
type: note
permalink: notes/this-is-a-tags-test
tags:
- '#basicmemory'
```

Issue 1: The literal tag has a `#` prepended, which makes the tag literally `#basicmemory`  in some PKMs. 

Issue 2: The tag notation isn't a YAML sequence because the list item (`- 'basicmemory'`) is not indented with two spaces. 

## Environment
- OS:  macOS 15.4.1
- Python version: 3.13.3
- Basic Memory version: 0.12.3
- Installation method: uv
- Claude Desktop version (if applicable): n/a

## Possible Solution

Ensure tag notation reflects the YAML spec. 

I'm working around this in Obsidian by using the Linter plugin to straighten out the tag YAML. It doesn't address quoting the text of the tag, but it does reindent correctly and remove the errant `#` from the string. 

[ex]: https://github.com/basicmachines-co/basic-memory?tab=readme-ov-file#how-it-works-in-practice
