### ISSUE TITLE
[BUG] Problems with MCP

### ISSUE THREAD

**Issue by vk2r** [basicmachines-co/basic-memory#190]
## Bug Description
I have been reviewing the MCP implementation and it appears that the MCP is incorrectly calling the server tools.

## Steps To Reproduce
1. Install docker version 0.14.0
2. Run command **docker compose up -d**
3. Install MCP in your MCP debugger tool
4. Use **list_memory_projects** / **get_current_project**
5. See error

## Expected Behavior
It is expected that the MCP methods will be able to function properly.

## Actual Behavior
The following errors have appeared:

![Image](https://github.com/user-attachments/assets/cc4bb4ab-a844-40ac-b87f-971d3b51bde5)

![Image](https://github.com/user-attachments/assets/4459cd93-ce4c-48c1-a83f-bfd75204304f)

## Environment
- OS: Proxmox 8.4.0
- Basic Memory version: 0.14.0
- Installation method: uvx

## Additional Context
```yml
services:
  basic-memory:
      image: ghcr.io/basicmachines-co/basic-memory:latest
      container_name: basic-memory-server
      ports:
        - 9000:8000
      volumes:
        - /mnt/obsidian-vault:/app/data:rw
        - ./basic-memory:/root/.basic-memory:rw
      environment:
        - BASIC_MEMORY_DEFAULT_PROJECT=main
        - BASIC_MEMORY_SYNC_CHANGES=true
        - BASIC_MEMORY_LOG_LEVEL=DEBUG
        - BASIC_MEMORY_SYNC_DELAY=1000
      restart: unless-stopped
```

## Other
I have discovered that the Docker documentation is also outdated. There are commands that no longer have the same name

```bash
**create should be replaced by add**
docker exec basic-memory-server basic-memory project create obsidian /app/data

**set-default should be replaced by add**
docker exec basic-memory-server basic-memory project set-default obsidian
```

## Possible Solution
Unfortunately BasicMemory is not very usable via MCP because of these problems.. Update the methods used in the MCP to match the basic-memory client configuration on the server.
